name: SaneAuctions
authors: [BadBones69, virustotalop]
main: com.clubobsidian.saneauctions.Main
version: "1.0.0"
depend: [Vault]
api-version: 1.13
description: >
  A plugin to auction off items globally.
commands:
  ca:
    description: Opens the Crazy Auctions GUI.
    aliases: [saneauction, saneauctions, crazyauction, crazyauctions, ah, auc, aucs, auction, auctions, hdv]